/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  theme: {
    extend: {
      colors: {
        brand: "var(--color-brand)",
        "brand-gradient": "var(--color-brand-gradient)",
        /* Palette (keep for legacy/raw usage) */
        "primary-900": "var(--color-primary-900)",
        "primary-700": "var(--color-primary-700)",
        "primary-500": "var(--color-primary-500)",
        "primary-300": "var(--color-primary-300)",
        "primary-100": "var(--color-primary-100)",
        "primary-50": "var(--color-primary-50)",
        headings: "var(--color-headings)",
        text: "var(--color-text)",
        white: "var(--color-white)",
        "white-soft": "var(--color-white-soft)",
        "gray-1000": "var(--color-gray-1000)",
        "gray-900": "var(--color-gray-900)",
        "gray-800": "var(--color-gray-800)",
        "gray-700": "var(--color-gray-700)",
        "gray-600": "var(--color-gray-600)",
        "gray-500": "var(--color-gray-500)",
        "gray-400": "var(--color-gray-400)",
        "gray-300": "var(--color-gray-300)",
        "gray-200": "var(--color-gray-200)",
        "gray-100": "var(--color-gray-100)",
        "secondary-pink-900": "var(--color-secondary-pink-900)",
        "secondary-pink-700": "var(--color-secondary-pink-700)",
        "secondary-pink-500": "var(--color-secondary-pink-500)",
        "secondary-pink-300": "var(--color-secondary-pink-300)",
        "secondary-pink-100": "var(--color-secondary-pink-100)",
        "secondary-orange-900": "var(--color-secondary-orange-900)",
        "secondary-orange-700": "var(--color-secondary-orange-700)",
        "secondary-orange-500": "var(--color-secondary-orange-500)",
        "secondary-orange-300": "var(--color-secondary-orange-300)",
        "secondary-orange-100": "var(--color-secondary-orange-100)",
        "secondary-blue-900": "var(--color-secondary-blue-900)",
        "secondary-blue-700": "var(--color-secondary-blue-700)",
        "secondary-blue-500": "var(--color-secondary-blue-500)",
        "secondary-blue-300": "var(--color-secondary-blue-300)",
        "secondary-blue-100": "var(--color-secondary-blue-100)",
        "secondary-yellow-900": "var(--color-secondary-yellow-900)",
        "secondary-yellow-700": "var(--color-secondary-yellow-700)",
        "secondary-yellow-500": "var(--color-secondary-yellow-500)",
        "secondary-yellow-300": "var(--color-secondary-yellow-300)",
        "secondary-yellow-100": "var(--color-secondary-yellow-100)",
        "secondary-green-900": "var(--color-secondary-green-900)",
        "secondary-green-700": "var(--color-secondary-green-700)",
        "secondary-green-500": "var(--color-secondary-green-500)",
        "secondary-green-300": "var(--color-secondary-green-300)",
        "secondary-green-100": "var(--color-secondary-green-100)",
        "secondary-red-900": "var(--color-secondary-red-900)",
        "secondary-red-700": "var(--color-secondary-red-700)",
        "secondary-red-500": "var(--color-secondary-red-500)",
        "secondary-red-300": "var(--color-secondary-red-300)",
        "secondary-red-100": "var(--color-secondary-red-100)",
        /* Semantic surfaces */
        surface: {
          DEFAULT: "var(--surface-page)",
          page: "var(--surface-page)",
          card: "var(--surface-card)",
          raised: "var(--surface-raised)",
          muted: "var(--surface-muted)",
          strong: "var(--surface-strong)",
          contrast: "var(--surface-contrast)",
        },
        /* Semantic text */
        ink: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          inverse: "var(--text-inverse)",
          accent: "var(--text-accent)",
          "on-strong": "var(--text-on-strong)",
        },
        /* Borders / dividers */
        border: {
          subtle: "var(--border-subtle)",
          DEFAULT: "var(--border-default)",
          strong: "var(--border-strong)",
          contrast: "var(--border-contrast)",
        },
        divider: "var(--divider)",
        /* Actions */
        action: {
          primary: "var(--action-primary)",
          "primary-hover": "var(--action-primary-hover)",
          "primary-active": "var(--action-primary-active)",
          "primary-on": "var(--action-primary-on)",
          secondary: "var(--action-secondary)",
          "secondary-hover": "var(--action-secondary-hover)",
          "secondary-active": "var(--action-secondary-active)",
          "secondary-on": "var(--action-secondary-on)",
          ghost: "var(--action-ghost)",
          "ghost-hover": "var(--action-ghost-hover)",
          "ghost-on": "var(--action-ghost-on)",
          link: "var(--action-link)",
          "link-hover": "var(--action-link-hover)",
          "link-visited": "var(--action-link-visited)",
        },
        /* Fields */
        field: {
          bg: "var(--field-bg)",
          border: "var(--field-border)",
          "border-focus": "var(--field-border-focus)",
          placeholder: "var(--field-placeholder)",
        },
        /* Status tokens */
        status: {
          info: "var(--status-info)",
          "info-surface": "var(--status-info-surface)",
          "info-on": "var(--status-info-on)",
          success: "var(--status-success)",
          "success-surface": "var(--status-success-surface)",
          "success-on": "var(--status-success-on)",
          warning: "var(--status-warning)",
          "warning-surface": "var(--status-warning-surface)",
          "warning-on": "var(--status-warning-on)",
          danger: "var(--status-danger)",
          "danger-surface": "var(--status-danger-surface)",
          "danger-on": "var(--status-danger-on)",
        },
        /* Code */
        code: {
          bg: "var(--code-bg)",
          border: "var(--code-border)",
          text: "var(--code-text)",
        },
        overlay: {
          scrim: "var(--overlay-scrim)",
        },
      },
      boxShadow: {
        "brand-01": "var(--shadow-01)",
        "brand-02": "var(--shadow-02)",
        "brand-03": "var(--shadow-03)",
        "brand-04": "var(--shadow-04)",
        "brand-05": "var(--shadow-05)",
        "brand-06": "var(--shadow-06)",
      },
      backgroundImage: {
        "brand-gradient": "var(--color-brand-gradient)",
      },
      fontFamily: {
        heading: "var(--font-family-heading)",
        body: "var(--font-family-body)",
      },
      fontSize: {
        "display-1": [
          "var(--font-display-1-size)",
          { lineHeight: "var(--font-display-1-line-height)", fontWeight: "var(--font-display-1-weight)" },
        ],
        "display-2": [
          "var(--font-display-2-size)",
          { lineHeight: "var(--font-display-2-line-height)", fontWeight: "var(--font-display-2-weight)" },
        ],
        "display-3": [
          "var(--font-display-3-size)",
          { lineHeight: "var(--font-display-3-line-height)", fontWeight: "var(--font-display-3-weight)" },
        ],
        "display-4": [
          "var(--font-display-4-size)",
          { lineHeight: "var(--font-display-4-line-height)", fontWeight: "var(--font-display-4-weight)" },
        ],
        h1: ["var(--font-h1-size)", { lineHeight: "var(--font-h1-line-height)", fontWeight: "var(--font-h1-weight)" }],
        h2: ["var(--font-h2-size)", { lineHeight: "var(--font-h2-line-height)", fontWeight: "var(--font-h2-weight)" }],
        h3: ["var(--font-h3-size)", { lineHeight: "var(--font-h3-line-height)", fontWeight: "var(--font-h3-weight)" }],
        h4: ["var(--font-h4-size)", { lineHeight: "var(--font-h4-line-height)", fontWeight: "var(--font-h4-weight)" }],
        h5: ["var(--font-h5-size)", { lineHeight: "var(--font-h5-line-height)", fontWeight: "var(--font-h5-weight)" }],
        h6: ["var(--font-h6-size)", { lineHeight: "var(--font-h6-line-height)", fontWeight: "var(--font-h6-weight)" }],
        "body-lg": [
          "var(--font-body-lg-size)",
          { lineHeight: "var(--font-body-lg-line-height)", fontWeight: "var(--font-body-lg-weight)" },
        ],
        "body-md": [
          "var(--font-body-md-size)",
          { lineHeight: "var(--font-body-md-line-height)", fontWeight: "var(--font-body-md-weight)" },
        ],
        "body-sm": [
          "var(--font-body-sm-size)",
          { lineHeight: "var(--font-body-sm-line-height)", fontWeight: "var(--font-body-sm-weight)" },
        ],
        "body-xs": [
          "var(--font-body-xs-size)",
          { lineHeight: "var(--font-body-xs-line-height)", fontWeight: "var(--font-body-xs-weight)" },
        ],
        link: ["var(--font-link-size)", { lineHeight: "var(--font-link-line-height)", fontWeight: "var(--font-link-weight)" }],
      },
    },
  },
};
